<a href="https://colab.research.google.com/github/Abhishek315-a/machine-larning-models/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧮 **What is NumPy?**

NumPy stands for Numerical Python.
It’s a **Python library** used for **numerical and scientific computing** — especially when dealing with large amounts of data.

It provides:

* A powerful n-dimensional array object (ndarray)

* Tools for mathematical, logical, and statistical operations

* Functions for linear algebra, Fourier transforms, and random number generation

#🔹 Why Use NumPy?

Because it’s much faster and more efficient than regular Python lists.

Let’s compare 👇

Without NumPy (using lists)

In [ ]:
my_list = [1, 2, 3, 4, 5]
result = [x * 2 for x in my_list]
print(result)


[2, 4, 6, 8, 10]


With NumPy

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr * 2)


[ 2  4  6  8 10]


✅ NumPy arrays are faster and can do element-wise operations directly (no loops needed!).

#🔹 Key Features of NumPy
| Feature                    | Description                                    |
| -------------------------- | ---------------------------------------------- |
| **ndarray**                | Multi-dimensional array object                 |
| **Broadcasting**           | Apply operations to arrays of different shapes |
| **Vectorization**          | Perform fast element-wise operations           |
| **Mathematical functions** | `sum()`, `mean()`, `sqrt()`, etc.              |
| **Linear Algebra**         | Matrix multiplication, inversion, eigenvalues  |
| **Random Module**          | Random numbers, distributions, sampling        |


In [ ]:
print(np.__version__)

2.0.2


In [ ]:
import numpy as np
print(np.__version__)

2.3.3


# Zero Dimensional Array

In [ ]:
arr = np.array('Abhishek')

In [ ]:
arr

array('Abhishek', dtype='<U8')

In [ ]:
print(arr.ndim)

0


# 1 Dimensional Array

In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


# 2 Dimensional Array

In [ ]:
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])

In [ ]:
print(arr)
print('Dimension : ',arr.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Dimension :  2


# 3 Dimension Array

In [ ]:
arr = np.array([[[1,2],[3,4]],
                [[12,23],[43,54]],
                [[23,43],[87,67]]])

In [ ]:
print(arr)
print('Dimension : ',arr.ndim)
print(arr.shape)

[[[ 1  2]
  [ 3  4]]

 [[12 23]
  [43 54]]

 [[23 43]
  [87 67]]]
Dimension :  3
(3, 2, 2)


In [ ]:
print(arr[0][0][0]) # chain indexing
print(arr[0,0,0]) # numpy indexing it is faster
# both are same

1
1


# 🧮 What is Slicing in NumPy?

Slicing means extracting a part (subset) of an array.
It works just like Python list slicing, but with extra power for multi-dimensional arrays.

# 🔹 Basic Syntax
array[start:stop:step]
| Part    | Meaning                   |
| ------- | ------------------------- |
| `start` | Starting index (included) |
| `stop`  | Ending index (excluded)   |
| `step`  | Step size (optional)      |


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[1:4])     # Elements from index 1 to 3 → [20 30 40]
print(arr[:3])      # From start to index 2 → [10 20 30]
print(arr[3:])      # From index 3 to end → [40 50 60]
print(arr[::2])     # Every 2nd element → [10 30 50]
print(arr[::-1])    # Reversed array → [60 50 40 30 20 10]


[20 30 40]
[10 20 30]
[40 50 60]
[10 30 50]
[60 50 40 30 20 10]


In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Entire 2nd row
print(arr[1, :])        # [5 6 7 8]

# Entire 3rd column
print(arr[:, 2])        # [ 3 7 11]

# Subarray (first 2 rows, first 3 columns)
print(arr[0:2, 0:3])
# [[1 2 3]
#  [5 6 7]]

# Last two rows and last two columns
print(arr[1:, 2:])
# [[ 7 8]
#  [11 12]]


[5 6 7 8]
[ 3  7 11]
[[1 2 3]
 [5 6 7]]
[[ 7  8]
 [11 12]]


#🧮 What are Arithmetic Operations in NumPy?

NumPy allows you to perform mathematical operations directly on arrays, element by element — without using loops.

This is called vectorization, and it makes calculations extremely fast ⚡.

# 🔹 Example 1: Basic Arithmetic

In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print(a + b)   # [11 22 33 44]
print(a - b)   # [ 9 18 27 36]
print(a * b)   # [10 40 90 160]
print(a / b)   # [10.   10.   10.   10.]
print(a % b)   # [0 0 0 0]
#✅ Operations happen element-wise
#(i.e., first element of a with first of b, second with second, etc.)


[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[0 0 0 0]


#🔹 Example 2: Scalar Operations

You can perform operations with a single number (scalar):

In [ ]:
a = np.array([10, 20, 30])

print(a + 5)   # [15 25 35]
print(a * 2)   # [20 40 60]
print(a / 10)  # [1. 2. 3.]
#👉 The scalar is broadcasted to every element (thanks to NumPy’s broadcasting feature).

[15 25 35]
[20 40 60]
[1. 2. 3.]


# 🔹 Example 3: Arithmetic on 2D Arrays

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A + B)
# [[ 6  8]
#  [10 12]]

print(A * B)
# [[ 5 12]
#  [21 32]]

print(A / B)
# [[0.2        0.33333333]
#  [0.42857143 0.5       ]]


[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


# 🔹 Example 4: Using NumPy Mathematical Functions

NumPy provides many built-in functions for element-wise math:

In [ ]:
a = np.array([1, 4, 9, 16])

print(np.sqrt(a))   # [1. 2. 3. 4.]
print(np.exp(a))    # e^x
print(np.log(a))    # natural log
print(np.sin(a))    # sine values
print(np.mean(a))   # average = 7.5
print(np.max(a))    # 16
print(np.sum(a))    # 30


[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[0.         1.38629436 2.19722458 2.77258872]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
7.5
16
30


# 🔹 Example 5: Matrix Multiplication

Element-wise multiplication (*) is not matrix multiplication.

For actual matrix multiplication, use:

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))
# or equivalently:
print(A @ B)


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


# 🔹 Example 6: Broadcasting (Different Shapes)

NumPy can automatically match array shapes to perform arithmetic:

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([10, 20, 30])

print(A + B)
# [[11 22 33]
#  [14 25 36]]
# 🔸 B is broadcasted across each row of A.


[[11 22 33]
 [14 25 36]]


| Operation             | Symbol            | Example  | Result                        |
| --------------------- | ----------------- | -------- | ----------------------------- |
| Addition              | `+`               | `a + b`  | Element-wise sum              |
| Subtraction           | `-`               | `a - b`  | Element-wise difference       |
| Multiplication        | `*`               | `a * b`  | Element-wise product          |
| Division              | `/`               | `a / b`  | Element-wise division         |
| Power                 | `**`              | `a ** 2` | Square of each element        |
| Matrix Multiplication | `@` or `np.dot()` | `A @ B`  | Linear algebra multiplication |


In [ ]:
array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
print(array1.shape)
print(array2.shape)

(1, 10)
(10, 1)


In [ ]:
print(array1*array2)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


# Filtering
in NumPy means selecting elements from an array that meet certain conditions — kind of like applying a filter to extract only the values you want.

🧠 1. Basic Concept

Filtering is usually done using boolean indexing.
You create a boolean array (True/False) based on a condition, and then use it to index the main array.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Filter elements greater than 25
filter_arr = arr > 25

print(filter_arr)
# Output: [False False  True  True  True]

print(arr[filter_arr])
# Output: [30 40 50]


[False False  True  True  True]
[30 40 50]


# Random Number

In [22]:
rng = np.random.default_rng()
print(rng.integers(1,7))

2


In [27]:
print(np.random.uniform())

0.7724093675227789


In [33]:
print(np.random.uniform(low=1,high=100))

73.00538044260142


In [34]:
array=np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [35]:
rng = np.random.default_rng()
rng.shuffle(array)
print(array)

[2 3 4 5 1]


In [42]:
fruits = np.array(['apple','banana','coconut','pineapple','orange'])
fruit = rng.choice(fruits)
fruit = rng.choice(fruits,size=(3))
fruit = rng.choice(fruits,size=(3,3))
print(fruit)

[['banana' 'pineapple' 'apple']
 ['pineapple' 'orange' 'pineapple']
 ['banana' 'coconut' 'orange']]
